[project]
name = "bad-appdf"
version = "0.1.0"
description = "Make a PDF file that plays Bad Apple"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.11.0.86",
    "pymupdf>=1.24.10",
]
